#378: prevent opening port for ANSI and ISO in one time
Lepidopterarium/chrysalis-api pull request #28
Opened 2019-07-09 20:14 UTC by 0957758592

As we are using `isDeviceSupported(port)` in ANSI and ISO keyboard types - there were been collapsed  - the port trying to oprening in one time for both and doesn't allow to open it for any of them.
This command should use once in chrysalis-focus.

Also will update `App.js` with small changes  in [Chrysalis](https://github.com/keyboardio/Chrysalis/issues/378) as clearing localStorage

2019-07-14 13:26 UTC, algernon requested changes
The entire point of delegating `isDeviceSupported()` to the hardware plugins was to make it generic, and not tied to any particular hardware. Doing `hardware.layout` from `focus.isDeviceSupported()` goes against that, and prevents us from supporting keyboards that would need some other command.

As an example, the Planck has AVR and ARM variants, and while we only support the AVR one, we will support the ARM one in the future too. To differentiate between the two, I planned to use a Focus command, and the respective Chrysalis hardware package would call that. That is, we have this use-case, which doesn't need `hardware.layout`. The planck also has two layouts (grid and MIT), so there's even more variety there.

We also want to support the case where two boards have the same VID/PID pair (like the Planck and KBD4x) - again, it's more than just `hardware.layout`.

So I _really_, _really_ want to keep `isDeviceSupported` delegated to the hardware packages. If the problem is that we try to open the same device twice, while we still have it open from the first check, we should fix _that_ problem. Perhaps introduce delays, check one or two devices a second or so, if we can't reliably `await` the close.

2019-07-15 12:29 UTC, 0957758592 commented
Fixed!

2019-07-15 12:49 UTC, algernon approved these changes
Looks good now, thank you!

2019-07-15 12:49 UTC, merged

2019-07-15 16:34 UTC, 0957758592 commented
Thank you @algernon 
btw also should merge this [PR](https://github.com/keyboardio/Chrysalis/pull/410) on the Chrysalis;
to clear localStorage.
there are just two changes in one file.